export const STEPS = {
  START: "START",
  SERVICE: "SERVICE",
  VEHICLE_TYPE: "VEHICLE_TYPE",
  VEHICLE_DATA: "VEHICLE_DATA",
  DATE: "DATE",
  TIME: "TIME",
  CONFIRM: "CONFIRM",
  DONE: "DONE",
};
