export const STEPS = {
  START: "START",
  HOME: "HOME", // не використовується поки що
  SERVICE: "SERVICE",
  VEHICLE_GROUP: "VEHICLE_GROUP",
  VEHICLE_TYPE: "VEHICLE_TYPE",
  OPTIONS: "OPTIONS",
  VEHICLE_DATA: "VEHICLE_DATA",
  DATE: "DATE",
  TIME: "TIME",
  PHONE: "PHONE",
  CONFIRM: "CONFIRM",
  DONE: "DONE",
  OTHER_CONTACT: "OTHER_CONTACT",
};
